services:
  - type: web
    name: alerta-backend
    rootDir: backend
    env: node
    plan: starter
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        value: clave_super_segura
      - key: ALLOWED_ORIGIN
        value: "*"
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 5
    autoDeploy: true

  - type: web
    name: alerta-frontend
    rootDir: frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://api-placeholder.onrender.com

    envVars:
      - key: VITE_API_URL
        fromService:
          name: alerta-backend
          type: web
          property: url

